### ISSUE TITLE
Ho to connect the inverter to serial 1?

### ISSUE THREAD

**Issue by ppernias** [MHassanNadeem/WatchPower#1]
I am using the MasterPower inverter Omega 5000 (MP-5K-24) at home, and I would love to connect a photon to it in order to expose the data logs but I am not quite sure how to connect the serial port of the photon to the inverter. 

Can you help me with this? Some pictures might help as well.

Thank you

**Comment by MHassanNadeem** [comment]
Your inverter should have come with a cable that exposes the serial with a DB9 connector. The cable should look like the following:
https://www.amazon.com/Cisco-72-3383-01-Console-Cable-RJ45-to-DB9/dp/B000GL3MOY

To connect to the photon you would require a RS232 to TTL converter, like the one [here](https://www.amazon.com/RS232-converter-board-Female-3-3V/dp/B005D5T292).
